apiVersion: v1
kind: ReplicationController
metatdata:
   name: rc-web
   labels:
     app: rc-web
spec:
 replicas: 3
 selector: 
  app: webapp
 template:
  metadata:
    name: webapp
    labels:
     app: webapp
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      ports:
       containerPort: 80
       protocol: TCP
