apiVersion:  v1 
kind:  ReplicationController 
metadata:
   name: rc-tapp
   labels:
     app: rc-tapp 
spec:
  replicas: 3
  selector:
    #matchlabels:
    app: tapp 
  template:
    metadata: 
      name: tapp
      labels:
        app: tapp 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80